//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudyHoa_Client_.ObjectServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ObjectServiceReference.IObjectsService")]
    public interface IObjectsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObjectsService/DeleteObject", ReplyAction="http://tempuri.org/IObjectsService/DeleteObjectResponse")]
        void DeleteObject(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObjectsService/DeleteObject", ReplyAction="http://tempuri.org/IObjectsService/DeleteObjectResponse")]
        System.Threading.Tasks.Task DeleteObjectAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObjectsService/EditObject", ReplyAction="http://tempuri.org/IObjectsService/EditObjectResponse")]
        void EditObject(int id, string objectNumber, int parentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObjectsService/EditObject", ReplyAction="http://tempuri.org/IObjectsService/EditObjectResponse")]
        System.Threading.Tasks.Task EditObjectAsync(int id, string objectNumber, int parentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObjectsService/AddObject", ReplyAction="http://tempuri.org/IObjectsService/AddObjectResponse")]
        int AddObject(int hoa_id, int type_object, string objectNumber, int parentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObjectsService/AddObject", ReplyAction="http://tempuri.org/IObjectsService/AddObjectResponse")]
        System.Threading.Tasks.Task<int> AddObjectAsync(int hoa_id, int type_object, string objectNumber, int parentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObjectsService/getAllObjects", ReplyAction="http://tempuri.org/IObjectsService/getAllObjectsResponse")]
        System.Data.DataSet getAllObjects(int hoaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObjectsService/getAllObjects", ReplyAction="http://tempuri.org/IObjectsService/getAllObjectsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> getAllObjectsAsync(int hoaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObjectsService/getObjectsStructure", ReplyAction="http://tempuri.org/IObjectsService/getObjectsStructureResponse")]
        System.Data.DataSet getObjectsStructure(int hoa_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObjectsService/getObjectsStructure", ReplyAction="http://tempuri.org/IObjectsService/getObjectsStructureResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> getObjectsStructureAsync(int hoa_id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IObjectsServiceChannel : CloudyHoa_Client_.ObjectServiceReference.IObjectsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObjectsServiceClient : System.ServiceModel.ClientBase<CloudyHoa_Client_.ObjectServiceReference.IObjectsService>, CloudyHoa_Client_.ObjectServiceReference.IObjectsService {
        
        public ObjectsServiceClient() {
        }
        
        public ObjectsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ObjectsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ObjectsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ObjectsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DeleteObject(int id) {
            base.Channel.DeleteObject(id);
        }
        
        public System.Threading.Tasks.Task DeleteObjectAsync(int id) {
            return base.Channel.DeleteObjectAsync(id);
        }
        
        public void EditObject(int id, string objectNumber, int parentId) {
            base.Channel.EditObject(id, objectNumber, parentId);
        }
        
        public System.Threading.Tasks.Task EditObjectAsync(int id, string objectNumber, int parentId) {
            return base.Channel.EditObjectAsync(id, objectNumber, parentId);
        }
        
        public int AddObject(int hoa_id, int type_object, string objectNumber, int parentId) {
            return base.Channel.AddObject(hoa_id, type_object, objectNumber, parentId);
        }
        
        public System.Threading.Tasks.Task<int> AddObjectAsync(int hoa_id, int type_object, string objectNumber, int parentId) {
            return base.Channel.AddObjectAsync(hoa_id, type_object, objectNumber, parentId);
        }
        
        public System.Data.DataSet getAllObjects(int hoaId) {
            return base.Channel.getAllObjects(hoaId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getAllObjectsAsync(int hoaId) {
            return base.Channel.getAllObjectsAsync(hoaId);
        }
        
        public System.Data.DataSet getObjectsStructure(int hoa_id) {
            return base.Channel.getObjectsStructure(hoa_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getObjectsStructureAsync(int hoa_id) {
            return base.Channel.getObjectsStructureAsync(hoa_id);
        }
    }
}
