//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudyHoa_Client_.SPService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SPService.IStaticParamsService")]
    public interface IStaticParamsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticParamsService/AddStaticParam", ReplyAction="http://tempuri.org/IStaticParamsService/AddStaticParamResponse")]
        void AddStaticParam(string value, int typeParams, int propertyId, int objectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticParamsService/AddStaticParam", ReplyAction="http://tempuri.org/IStaticParamsService/AddStaticParamResponse")]
        System.Threading.Tasks.Task AddStaticParamAsync(string value, int typeParams, int propertyId, int objectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticParamsService/DeleteStaticParam", ReplyAction="http://tempuri.org/IStaticParamsService/DeleteStaticParamResponse")]
        void DeleteStaticParam(int paramId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticParamsService/DeleteStaticParam", ReplyAction="http://tempuri.org/IStaticParamsService/DeleteStaticParamResponse")]
        System.Threading.Tasks.Task DeleteStaticParamAsync(int paramId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticParamsService/GetStaticParam", ReplyAction="http://tempuri.org/IStaticParamsService/GetStaticParamResponse")]
        System.Data.DataSet GetStaticParam(int paramId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticParamsService/GetStaticParam", ReplyAction="http://tempuri.org/IStaticParamsService/GetStaticParamResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetStaticParamAsync(int paramId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticParamsService/GetCurrentStaticParam", ReplyAction="http://tempuri.org/IStaticParamsService/GetCurrentStaticParamResponse")]
        System.Data.DataSet GetCurrentStaticParam(int propId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticParamsService/GetCurrentStaticParam", ReplyAction="http://tempuri.org/IStaticParamsService/GetCurrentStaticParamResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetCurrentStaticParamAsync(int propId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticParamsService/GetCurrentStaticParams", ReplyAction="http://tempuri.org/IStaticParamsService/GetCurrentStaticParamsResponse")]
        System.Data.DataSet GetCurrentStaticParams(int objectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticParamsService/GetCurrentStaticParams", ReplyAction="http://tempuri.org/IStaticParamsService/GetCurrentStaticParamsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetCurrentStaticParamsAsync(int objectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticParamsService/GetOldStaticParams", ReplyAction="http://tempuri.org/IStaticParamsService/GetOldStaticParamsResponse")]
        System.Data.DataSet GetOldStaticParams(int objectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticParamsService/GetOldStaticParams", ReplyAction="http://tempuri.org/IStaticParamsService/GetOldStaticParamsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetOldStaticParamsAsync(int objectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticParamsService/GetSchemeStaticParams", ReplyAction="http://tempuri.org/IStaticParamsService/GetSchemeStaticParamsResponse")]
        System.Data.DataSet GetSchemeStaticParams(int hoaId, int typeObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticParamsService/GetSchemeStaticParams", ReplyAction="http://tempuri.org/IStaticParamsService/GetSchemeStaticParamsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetSchemeStaticParamsAsync(int hoaId, int typeObject);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStaticParamsServiceChannel : CloudyHoa_Client_.SPService.IStaticParamsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StaticParamsServiceClient : System.ServiceModel.ClientBase<CloudyHoa_Client_.SPService.IStaticParamsService>, CloudyHoa_Client_.SPService.IStaticParamsService {
        
        public StaticParamsServiceClient() {
        }
        
        public StaticParamsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StaticParamsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StaticParamsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StaticParamsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddStaticParam(string value, int typeParams, int propertyId, int objectId) {
            base.Channel.AddStaticParam(value, typeParams, propertyId, objectId);
        }
        
        public System.Threading.Tasks.Task AddStaticParamAsync(string value, int typeParams, int propertyId, int objectId) {
            return base.Channel.AddStaticParamAsync(value, typeParams, propertyId, objectId);
        }
        
        public void DeleteStaticParam(int paramId) {
            base.Channel.DeleteStaticParam(paramId);
        }
        
        public System.Threading.Tasks.Task DeleteStaticParamAsync(int paramId) {
            return base.Channel.DeleteStaticParamAsync(paramId);
        }
        
        public System.Data.DataSet GetStaticParam(int paramId) {
            return base.Channel.GetStaticParam(paramId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetStaticParamAsync(int paramId) {
            return base.Channel.GetStaticParamAsync(paramId);
        }
        
        public System.Data.DataSet GetCurrentStaticParam(int propId) {
            return base.Channel.GetCurrentStaticParam(propId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetCurrentStaticParamAsync(int propId) {
            return base.Channel.GetCurrentStaticParamAsync(propId);
        }
        
        public System.Data.DataSet GetCurrentStaticParams(int objectId) {
            return base.Channel.GetCurrentStaticParams(objectId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetCurrentStaticParamsAsync(int objectId) {
            return base.Channel.GetCurrentStaticParamsAsync(objectId);
        }
        
        public System.Data.DataSet GetOldStaticParams(int objectId) {
            return base.Channel.GetOldStaticParams(objectId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetOldStaticParamsAsync(int objectId) {
            return base.Channel.GetOldStaticParamsAsync(objectId);
        }
        
        public System.Data.DataSet GetSchemeStaticParams(int hoaId, int typeObject) {
            return base.Channel.GetSchemeStaticParams(hoaId, typeObject);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetSchemeStaticParamsAsync(int hoaId, int typeObject) {
            return base.Channel.GetSchemeStaticParamsAsync(hoaId, typeObject);
        }
    }
}
