//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudyHoa_Client_.PAService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PAService.IPersonalAccountService")]
    public interface IPersonalAccountService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonalAccountService/AddPersonalAccount", ReplyAction="http://tempuri.org/IPersonalAccountService/AddPersonalAccountResponse")]
        void AddPersonalAccount(string account, int objectId, int ownerId, int registered, int lives);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonalAccountService/AddPersonalAccount", ReplyAction="http://tempuri.org/IPersonalAccountService/AddPersonalAccountResponse")]
        System.Threading.Tasks.Task AddPersonalAccountAsync(string account, int objectId, int ownerId, int registered, int lives);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonalAccountService/DeletePersonalAccount", ReplyAction="http://tempuri.org/IPersonalAccountService/DeletePersonalAccountResponse")]
        void DeletePersonalAccount(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonalAccountService/DeletePersonalAccount", ReplyAction="http://tempuri.org/IPersonalAccountService/DeletePersonalAccountResponse")]
        System.Threading.Tasks.Task DeletePersonalAccountAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonalAccountService/EditPersonalAccount", ReplyAction="http://tempuri.org/IPersonalAccountService/EditPersonalAccountResponse")]
        void EditPersonalAccount(int id, string account, int objectId, int ownerId, int registered, int lives);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonalAccountService/EditPersonalAccount", ReplyAction="http://tempuri.org/IPersonalAccountService/EditPersonalAccountResponse")]
        System.Threading.Tasks.Task EditPersonalAccountAsync(int id, string account, int objectId, int ownerId, int registered, int lives);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonalAccountService/GetPersonalAccounts", ReplyAction="http://tempuri.org/IPersonalAccountService/GetPersonalAccountsResponse")]
        System.Data.DataSet GetPersonalAccounts(int objectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonalAccountService/GetPersonalAccounts", ReplyAction="http://tempuri.org/IPersonalAccountService/GetPersonalAccountsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetPersonalAccountsAsync(int objectId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPersonalAccountServiceChannel : CloudyHoa_Client_.PAService.IPersonalAccountService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonalAccountServiceClient : System.ServiceModel.ClientBase<CloudyHoa_Client_.PAService.IPersonalAccountService>, CloudyHoa_Client_.PAService.IPersonalAccountService {
        
        public PersonalAccountServiceClient() {
        }
        
        public PersonalAccountServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonalAccountServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonalAccountServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonalAccountServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddPersonalAccount(string account, int objectId, int ownerId, int registered, int lives) {
            base.Channel.AddPersonalAccount(account, objectId, ownerId, registered, lives);
        }
        
        public System.Threading.Tasks.Task AddPersonalAccountAsync(string account, int objectId, int ownerId, int registered, int lives) {
            return base.Channel.AddPersonalAccountAsync(account, objectId, ownerId, registered, lives);
        }
        
        public void DeletePersonalAccount(int id) {
            base.Channel.DeletePersonalAccount(id);
        }
        
        public System.Threading.Tasks.Task DeletePersonalAccountAsync(int id) {
            return base.Channel.DeletePersonalAccountAsync(id);
        }
        
        public void EditPersonalAccount(int id, string account, int objectId, int ownerId, int registered, int lives) {
            base.Channel.EditPersonalAccount(id, account, objectId, ownerId, registered, lives);
        }
        
        public System.Threading.Tasks.Task EditPersonalAccountAsync(int id, string account, int objectId, int ownerId, int registered, int lives) {
            return base.Channel.EditPersonalAccountAsync(id, account, objectId, ownerId, registered, lives);
        }
        
        public System.Data.DataSet GetPersonalAccounts(int objectId) {
            return base.Channel.GetPersonalAccounts(objectId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetPersonalAccountsAsync(int objectId) {
            return base.Channel.GetPersonalAccountsAsync(objectId);
        }
    }
}
