//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudyHoa_Client_.SPServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SPServiceReference.IStaticParamsService")]
    public interface IStaticParamsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticParamsService/addStaticParam", ReplyAction="http://tempuri.org/IStaticParamsService/addStaticParamResponse")]
        void addStaticParam(string value, int typeParams, int propertyId, System.DateTime startPeriod, System.DateTime changingDate, int objectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticParamsService/addStaticParam", ReplyAction="http://tempuri.org/IStaticParamsService/addStaticParamResponse")]
        System.Threading.Tasks.Task addStaticParamAsync(string value, int typeParams, int propertyId, System.DateTime startPeriod, System.DateTime changingDate, int objectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticParamsService/deleteStaticParam", ReplyAction="http://tempuri.org/IStaticParamsService/deleteStaticParamResponse")]
        void deleteStaticParam(int paramId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticParamsService/deleteStaticParam", ReplyAction="http://tempuri.org/IStaticParamsService/deleteStaticParamResponse")]
        System.Threading.Tasks.Task deleteStaticParamAsync(int paramId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticParamsService/getStaticParam", ReplyAction="http://tempuri.org/IStaticParamsService/getStaticParamResponse")]
        System.Data.DataSet getStaticParam(int paramId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticParamsService/getStaticParam", ReplyAction="http://tempuri.org/IStaticParamsService/getStaticParamResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> getStaticParamAsync(int paramId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticParamsService/getCurrentStaticParam", ReplyAction="http://tempuri.org/IStaticParamsService/getCurrentStaticParamResponse")]
        System.Data.DataSet getCurrentStaticParam(int propId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticParamsService/getCurrentStaticParam", ReplyAction="http://tempuri.org/IStaticParamsService/getCurrentStaticParamResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> getCurrentStaticParamAsync(int propId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticParamsService/getCurrentStaticParams", ReplyAction="http://tempuri.org/IStaticParamsService/getCurrentStaticParamsResponse")]
        System.Data.DataSet getCurrentStaticParams(int objectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticParamsService/getCurrentStaticParams", ReplyAction="http://tempuri.org/IStaticParamsService/getCurrentStaticParamsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> getCurrentStaticParamsAsync(int objectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticParamsService/getOldStaticParams", ReplyAction="http://tempuri.org/IStaticParamsService/getOldStaticParamsResponse")]
        System.Data.DataSet getOldStaticParams(int objectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticParamsService/getOldStaticParams", ReplyAction="http://tempuri.org/IStaticParamsService/getOldStaticParamsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> getOldStaticParamsAsync(int objectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticParamsService/GetSchemeStaticParams", ReplyAction="http://tempuri.org/IStaticParamsService/GetSchemeStaticParamsResponse")]
        System.Data.DataSet GetSchemeStaticParams(int hoaId, int typeObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticParamsService/GetSchemeStaticParams", ReplyAction="http://tempuri.org/IStaticParamsService/GetSchemeStaticParamsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetSchemeStaticParamsAsync(int hoaId, int typeObject);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStaticParamsServiceChannel : CloudyHoa_Client_.SPServiceReference.IStaticParamsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StaticParamsServiceClient : System.ServiceModel.ClientBase<CloudyHoa_Client_.SPServiceReference.IStaticParamsService>, CloudyHoa_Client_.SPServiceReference.IStaticParamsService {
        
        public StaticParamsServiceClient() {
        }
        
        public StaticParamsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StaticParamsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StaticParamsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StaticParamsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void addStaticParam(string value, int typeParams, int propertyId, System.DateTime startPeriod, System.DateTime changingDate, int objectId) {
            base.Channel.addStaticParam(value, typeParams, propertyId, startPeriod, changingDate, objectId);
        }
        
        public System.Threading.Tasks.Task addStaticParamAsync(string value, int typeParams, int propertyId, System.DateTime startPeriod, System.DateTime changingDate, int objectId) {
            return base.Channel.addStaticParamAsync(value, typeParams, propertyId, startPeriod, changingDate, objectId);
        }
        
        public void deleteStaticParam(int paramId) {
            base.Channel.deleteStaticParam(paramId);
        }
        
        public System.Threading.Tasks.Task deleteStaticParamAsync(int paramId) {
            return base.Channel.deleteStaticParamAsync(paramId);
        }
        
        public System.Data.DataSet getStaticParam(int paramId) {
            return base.Channel.getStaticParam(paramId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getStaticParamAsync(int paramId) {
            return base.Channel.getStaticParamAsync(paramId);
        }
        
        public System.Data.DataSet getCurrentStaticParam(int propId) {
            return base.Channel.getCurrentStaticParam(propId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getCurrentStaticParamAsync(int propId) {
            return base.Channel.getCurrentStaticParamAsync(propId);
        }
        
        public System.Data.DataSet getCurrentStaticParams(int objectId) {
            return base.Channel.getCurrentStaticParams(objectId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getCurrentStaticParamsAsync(int objectId) {
            return base.Channel.getCurrentStaticParamsAsync(objectId);
        }
        
        public System.Data.DataSet getOldStaticParams(int objectId) {
            return base.Channel.getOldStaticParams(objectId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getOldStaticParamsAsync(int objectId) {
            return base.Channel.getOldStaticParamsAsync(objectId);
        }
        
        public System.Data.DataSet GetSchemeStaticParams(int hoaId, int typeObject) {
            return base.Channel.GetSchemeStaticParams(hoaId, typeObject);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetSchemeStaticParamsAsync(int hoaId, int typeObject) {
            return base.Channel.GetSchemeStaticParamsAsync(hoaId, typeObject);
        }
    }
}
