//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudyHoa_Client_.TariffService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TariffService.ITariffService")]
    public interface ITariffService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITariffService/AddTariff", ReplyAction="http://tempuri.org/ITariffService/AddTariffResponse")]
        void AddTariff(string name, float value, int metadataId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITariffService/AddTariff", ReplyAction="http://tempuri.org/ITariffService/AddTariffResponse")]
        System.Threading.Tasks.Task AddTariffAsync(string name, float value, int metadataId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITariffService/EditTariff", ReplyAction="http://tempuri.org/ITariffService/EditTariffResponse")]
        void EditTariff(int tariffId, string name, float value, int metadataId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITariffService/EditTariff", ReplyAction="http://tempuri.org/ITariffService/EditTariffResponse")]
        System.Threading.Tasks.Task EditTariffAsync(int tariffId, string name, float value, int metadataId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITariffService/DeleteTariff", ReplyAction="http://tempuri.org/ITariffService/DeleteTariffResponse")]
        void DeleteTariff(int tariffId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITariffService/DeleteTariff", ReplyAction="http://tempuri.org/ITariffService/DeleteTariffResponse")]
        System.Threading.Tasks.Task DeleteTariffAsync(int tariffId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITariffService/GetTariffs", ReplyAction="http://tempuri.org/ITariffService/GetTariffsResponse")]
        System.Data.DataSet GetTariffs(int hoaId, System.Nullable<int> type_object);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITariffService/GetTariffs", ReplyAction="http://tempuri.org/ITariffService/GetTariffsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetTariffsAsync(int hoaId, System.Nullable<int> type_object);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITariffService/GetServices", ReplyAction="http://tempuri.org/ITariffService/GetServicesResponse")]
        System.Data.DataSet GetServices(int hoaId, int type_object);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITariffService/GetServices", ReplyAction="http://tempuri.org/ITariffService/GetServicesResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetServicesAsync(int hoaId, int type_object);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITariffServiceChannel : CloudyHoa_Client_.TariffService.ITariffService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TariffServiceClient : System.ServiceModel.ClientBase<CloudyHoa_Client_.TariffService.ITariffService>, CloudyHoa_Client_.TariffService.ITariffService {
        
        public TariffServiceClient() {
        }
        
        public TariffServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TariffServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TariffServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TariffServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddTariff(string name, float value, int metadataId) {
            base.Channel.AddTariff(name, value, metadataId);
        }
        
        public System.Threading.Tasks.Task AddTariffAsync(string name, float value, int metadataId) {
            return base.Channel.AddTariffAsync(name, value, metadataId);
        }
        
        public void EditTariff(int tariffId, string name, float value, int metadataId) {
            base.Channel.EditTariff(tariffId, name, value, metadataId);
        }
        
        public System.Threading.Tasks.Task EditTariffAsync(int tariffId, string name, float value, int metadataId) {
            return base.Channel.EditTariffAsync(tariffId, name, value, metadataId);
        }
        
        public void DeleteTariff(int tariffId) {
            base.Channel.DeleteTariff(tariffId);
        }
        
        public System.Threading.Tasks.Task DeleteTariffAsync(int tariffId) {
            return base.Channel.DeleteTariffAsync(tariffId);
        }
        
        public System.Data.DataSet GetTariffs(int hoaId, System.Nullable<int> type_object) {
            return base.Channel.GetTariffs(hoaId, type_object);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetTariffsAsync(int hoaId, System.Nullable<int> type_object) {
            return base.Channel.GetTariffsAsync(hoaId, type_object);
        }
        
        public System.Data.DataSet GetServices(int hoaId, int type_object) {
            return base.Channel.GetServices(hoaId, type_object);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetServicesAsync(int hoaId, int type_object) {
            return base.Channel.GetServicesAsync(hoaId, type_object);
        }
    }
}
