//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudyHoa_Client_.DynamicParamsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DynamicParamsService.IDynamicParamsService")]
    public interface IDynamicParamsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDynamicParamsService/AddDynamicParam", ReplyAction="http://tempuri.org/IDynamicParamsService/AddDynamicParamResponse")]
        void AddDynamicParam(float value, System.DateTime period, int propertyId, int personalAccountId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDynamicParamsService/AddDynamicParam", ReplyAction="http://tempuri.org/IDynamicParamsService/AddDynamicParamResponse")]
        System.Threading.Tasks.Task AddDynamicParamAsync(float value, System.DateTime period, int propertyId, int personalAccountId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDynamicParamsService/OldDynamicParams", ReplyAction="http://tempuri.org/IDynamicParamsService/OldDynamicParamsResponse")]
        System.Data.DataSet OldDynamicParams(int typeObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDynamicParamsService/OldDynamicParams", ReplyAction="http://tempuri.org/IDynamicParamsService/OldDynamicParamsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> OldDynamicParamsAsync(int typeObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDynamicParamsService/OldAllDynamicParams", ReplyAction="http://tempuri.org/IDynamicParamsService/OldAllDynamicParamsResponse")]
        System.Data.DataSet OldAllDynamicParams(int hoaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDynamicParamsService/OldAllDynamicParams", ReplyAction="http://tempuri.org/IDynamicParamsService/OldAllDynamicParamsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> OldAllDynamicParamsAsync(int hoaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDynamicParamsService/SchemeDPTable", ReplyAction="http://tempuri.org/IDynamicParamsService/SchemeDPTableResponse")]
        System.Data.DataSet SchemeDPTable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDynamicParamsService/SchemeDPTable", ReplyAction="http://tempuri.org/IDynamicParamsService/SchemeDPTableResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SchemeDPTableAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDynamicParamsService/BoneDynamicParams", ReplyAction="http://tempuri.org/IDynamicParamsService/BoneDynamicParamsResponse")]
        System.Data.DataSet BoneDynamicParams(int typeObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDynamicParamsService/BoneDynamicParams", ReplyAction="http://tempuri.org/IDynamicParamsService/BoneDynamicParamsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> BoneDynamicParamsAsync(int typeObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDynamicParamsService/DynamicParametersTable", ReplyAction="http://tempuri.org/IDynamicParamsService/DynamicParametersTableResponse")]
        System.Data.DataSet DynamicParametersTable(int hoaId, int typeObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDynamicParamsService/DynamicParametersTable", ReplyAction="http://tempuri.org/IDynamicParamsService/DynamicParametersTableResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> DynamicParametersTableAsync(int hoaId, int typeObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDynamicParamsService/BoneDynamicParamsFromChildrens", ReplyAction="http://tempuri.org/IDynamicParamsService/BoneDynamicParamsFromChildrensResponse")]
        System.Data.DataSet BoneDynamicParamsFromChildrens(int objectId, int typeObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDynamicParamsService/BoneDynamicParamsFromChildrens", ReplyAction="http://tempuri.org/IDynamicParamsService/BoneDynamicParamsFromChildrensResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> BoneDynamicParamsFromChildrensAsync(int objectId, int typeObject);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDynamicParamsServiceChannel : CloudyHoa_Client_.DynamicParamsService.IDynamicParamsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DynamicParamsServiceClient : System.ServiceModel.ClientBase<CloudyHoa_Client_.DynamicParamsService.IDynamicParamsService>, CloudyHoa_Client_.DynamicParamsService.IDynamicParamsService {
        
        public DynamicParamsServiceClient() {
        }
        
        public DynamicParamsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DynamicParamsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DynamicParamsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DynamicParamsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddDynamicParam(float value, System.DateTime period, int propertyId, int personalAccountId) {
            base.Channel.AddDynamicParam(value, period, propertyId, personalAccountId);
        }
        
        public System.Threading.Tasks.Task AddDynamicParamAsync(float value, System.DateTime period, int propertyId, int personalAccountId) {
            return base.Channel.AddDynamicParamAsync(value, period, propertyId, personalAccountId);
        }
        
        public System.Data.DataSet OldDynamicParams(int typeObject) {
            return base.Channel.OldDynamicParams(typeObject);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> OldDynamicParamsAsync(int typeObject) {
            return base.Channel.OldDynamicParamsAsync(typeObject);
        }
        
        public System.Data.DataSet OldAllDynamicParams(int hoaId) {
            return base.Channel.OldAllDynamicParams(hoaId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> OldAllDynamicParamsAsync(int hoaId) {
            return base.Channel.OldAllDynamicParamsAsync(hoaId);
        }
        
        public System.Data.DataSet SchemeDPTable() {
            return base.Channel.SchemeDPTable();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SchemeDPTableAsync() {
            return base.Channel.SchemeDPTableAsync();
        }
        
        public System.Data.DataSet BoneDynamicParams(int typeObject) {
            return base.Channel.BoneDynamicParams(typeObject);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BoneDynamicParamsAsync(int typeObject) {
            return base.Channel.BoneDynamicParamsAsync(typeObject);
        }
        
        public System.Data.DataSet DynamicParametersTable(int hoaId, int typeObject) {
            return base.Channel.DynamicParametersTable(hoaId, typeObject);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DynamicParametersTableAsync(int hoaId, int typeObject) {
            return base.Channel.DynamicParametersTableAsync(hoaId, typeObject);
        }
        
        public System.Data.DataSet BoneDynamicParamsFromChildrens(int objectId, int typeObject) {
            return base.Channel.BoneDynamicParamsFromChildrens(objectId, typeObject);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BoneDynamicParamsFromChildrensAsync(int objectId, int typeObject) {
            return base.Channel.BoneDynamicParamsFromChildrensAsync(objectId, typeObject);
        }
    }
}
