//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudyHoa_Client_.CHService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CHService.ICHService")]
    public interface ICHService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICHService/GetCalculationHistoryFromObject", ReplyAction="http://tempuri.org/ICHService/GetCalculationHistoryFromObjectResponse")]
        System.Data.DataSet GetCalculationHistoryFromObject(int objectId, System.DateTime period);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICHService/GetCalculationHistoryFromObject", ReplyAction="http://tempuri.org/ICHService/GetCalculationHistoryFromObjectResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetCalculationHistoryFromObjectAsync(int objectId, System.DateTime period);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICHService/GetCalculationHistoryFromPA", ReplyAction="http://tempuri.org/ICHService/GetCalculationHistoryFromPAResponse")]
        System.Data.DataSet GetCalculationHistoryFromPA(int paId, System.DateTime period);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICHService/GetCalculationHistoryFromPA", ReplyAction="http://tempuri.org/ICHService/GetCalculationHistoryFromPAResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetCalculationHistoryFromPAAsync(int paId, System.DateTime period);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICHServiceChannel : CloudyHoa_Client_.CHService.ICHService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CHServiceClient : System.ServiceModel.ClientBase<CloudyHoa_Client_.CHService.ICHService>, CloudyHoa_Client_.CHService.ICHService {
        
        public CHServiceClient() {
        }
        
        public CHServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CHServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CHServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CHServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetCalculationHistoryFromObject(int objectId, System.DateTime period) {
            return base.Channel.GetCalculationHistoryFromObject(objectId, period);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetCalculationHistoryFromObjectAsync(int objectId, System.DateTime period) {
            return base.Channel.GetCalculationHistoryFromObjectAsync(objectId, period);
        }
        
        public System.Data.DataSet GetCalculationHistoryFromPA(int paId, System.DateTime period) {
            return base.Channel.GetCalculationHistoryFromPA(paId, period);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetCalculationHistoryFromPAAsync(int paId, System.DateTime period) {
            return base.Channel.GetCalculationHistoryFromPAAsync(paId, period);
        }
    }
}
