//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudyHoa_Client_.EHService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EHService.IEHService")]
    public interface IEHService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEHService/GetEnteringHistoryFromObject", ReplyAction="http://tempuri.org/IEHService/GetEnteringHistoryFromObjectResponse")]
        System.Data.DataSet GetEnteringHistoryFromObject(int objectId, System.DateTime period);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEHService/GetEnteringHistoryFromObject", ReplyAction="http://tempuri.org/IEHService/GetEnteringHistoryFromObjectResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetEnteringHistoryFromObjectAsync(int objectId, System.DateTime period);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEHService/GetEnteringHistoryFromPA", ReplyAction="http://tempuri.org/IEHService/GetEnteringHistoryFromPAResponse")]
        System.Data.DataSet GetEnteringHistoryFromPA(int paId, System.DateTime period);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEHService/GetEnteringHistoryFromPA", ReplyAction="http://tempuri.org/IEHService/GetEnteringHistoryFromPAResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetEnteringHistoryFromPAAsync(int paId, System.DateTime period);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEHServiceChannel : CloudyHoa_Client_.EHService.IEHService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EHServiceClient : System.ServiceModel.ClientBase<CloudyHoa_Client_.EHService.IEHService>, CloudyHoa_Client_.EHService.IEHService {
        
        public EHServiceClient() {
        }
        
        public EHServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EHServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EHServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EHServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetEnteringHistoryFromObject(int objectId, System.DateTime period) {
            return base.Channel.GetEnteringHistoryFromObject(objectId, period);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetEnteringHistoryFromObjectAsync(int objectId, System.DateTime period) {
            return base.Channel.GetEnteringHistoryFromObjectAsync(objectId, period);
        }
        
        public System.Data.DataSet GetEnteringHistoryFromPA(int paId, System.DateTime period) {
            return base.Channel.GetEnteringHistoryFromPA(paId, period);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetEnteringHistoryFromPAAsync(int paId, System.DateTime period) {
            return base.Channel.GetEnteringHistoryFromPAAsync(paId, period);
        }
    }
}
