//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudyHoa_Client_.ResidentsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ResidentsService.IApartmentResidents")]
    public interface IApartmentResidents {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApartmentResidents/AddResident", ReplyAction="http://tempuri.org/IApartmentResidents/AddResidentResponse")]
        void AddResident(string fullName, int objectId, bool registered, System.Nullable<System.DateTime> registration_date, bool residence, System.Nullable<System.DateTime> checkInDate, bool owner, System.Nullable<int> numenator, System.Nullable<int> denominator);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApartmentResidents/AddResident", ReplyAction="http://tempuri.org/IApartmentResidents/AddResidentResponse")]
        System.Threading.Tasks.Task AddResidentAsync(string fullName, int objectId, bool registered, System.Nullable<System.DateTime> registration_date, bool residence, System.Nullable<System.DateTime> checkInDate, bool owner, System.Nullable<int> numenator, System.Nullable<int> denominator);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApartmentResidents/EditResident", ReplyAction="http://tempuri.org/IApartmentResidents/EditResidentResponse")]
        void EditResident(int Id, string fullName, int objectId, bool registered, System.Nullable<System.DateTime> registration_date, bool residence, System.Nullable<System.DateTime> checkInDate, bool owner, System.Nullable<int> numenator, System.Nullable<int> denominator);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApartmentResidents/EditResident", ReplyAction="http://tempuri.org/IApartmentResidents/EditResidentResponse")]
        System.Threading.Tasks.Task EditResidentAsync(int Id, string fullName, int objectId, bool registered, System.Nullable<System.DateTime> registration_date, bool residence, System.Nullable<System.DateTime> checkInDate, bool owner, System.Nullable<int> numenator, System.Nullable<int> denominator);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApartmentResidents/DeleteResident", ReplyAction="http://tempuri.org/IApartmentResidents/DeleteResidentResponse")]
        void DeleteResident(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApartmentResidents/DeleteResident", ReplyAction="http://tempuri.org/IApartmentResidents/DeleteResidentResponse")]
        System.Threading.Tasks.Task DeleteResidentAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApartmentResidents/GetResidents", ReplyAction="http://tempuri.org/IApartmentResidents/GetResidentsResponse")]
        System.Data.DataSet GetResidents(int objectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApartmentResidents/GetResidents", ReplyAction="http://tempuri.org/IApartmentResidents/GetResidentsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetResidentsAsync(int objectId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IApartmentResidentsChannel : CloudyHoa_Client_.ResidentsService.IApartmentResidents, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApartmentResidentsClient : System.ServiceModel.ClientBase<CloudyHoa_Client_.ResidentsService.IApartmentResidents>, CloudyHoa_Client_.ResidentsService.IApartmentResidents {
        
        public ApartmentResidentsClient() {
        }
        
        public ApartmentResidentsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApartmentResidentsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApartmentResidentsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApartmentResidentsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddResident(string fullName, int objectId, bool registered, System.Nullable<System.DateTime> registration_date, bool residence, System.Nullable<System.DateTime> checkInDate, bool owner, System.Nullable<int> numenator, System.Nullable<int> denominator) {
            base.Channel.AddResident(fullName, objectId, registered, registration_date, residence, checkInDate, owner, numenator, denominator);
        }
        
        public System.Threading.Tasks.Task AddResidentAsync(string fullName, int objectId, bool registered, System.Nullable<System.DateTime> registration_date, bool residence, System.Nullable<System.DateTime> checkInDate, bool owner, System.Nullable<int> numenator, System.Nullable<int> denominator) {
            return base.Channel.AddResidentAsync(fullName, objectId, registered, registration_date, residence, checkInDate, owner, numenator, denominator);
        }
        
        public void EditResident(int Id, string fullName, int objectId, bool registered, System.Nullable<System.DateTime> registration_date, bool residence, System.Nullable<System.DateTime> checkInDate, bool owner, System.Nullable<int> numenator, System.Nullable<int> denominator) {
            base.Channel.EditResident(Id, fullName, objectId, registered, registration_date, residence, checkInDate, owner, numenator, denominator);
        }
        
        public System.Threading.Tasks.Task EditResidentAsync(int Id, string fullName, int objectId, bool registered, System.Nullable<System.DateTime> registration_date, bool residence, System.Nullable<System.DateTime> checkInDate, bool owner, System.Nullable<int> numenator, System.Nullable<int> denominator) {
            return base.Channel.EditResidentAsync(Id, fullName, objectId, registered, registration_date, residence, checkInDate, owner, numenator, denominator);
        }
        
        public void DeleteResident(int Id) {
            base.Channel.DeleteResident(Id);
        }
        
        public System.Threading.Tasks.Task DeleteResidentAsync(int Id) {
            return base.Channel.DeleteResidentAsync(Id);
        }
        
        public System.Data.DataSet GetResidents(int objectId) {
            return base.Channel.GetResidents(objectId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetResidentsAsync(int objectId) {
            return base.Channel.GetResidentsAsync(objectId);
        }
    }
}
